#!/bin/bash

# Author: Alexandra Aguirre
# Created: 6-11-18
# Root Interview

# =========================
# TrackDrivingHistory: test-all.sh
# =========================
# You can run this script at the command line like so:
#
#   bash test-all.sh
#
# For more details, see the README.md

for i in `seq 1 7`;
do
	echo -n "Checking TestCase0$i... "

	# Attempt to compile.
	javac TrackDrivingHistory.java
    Java TrackDrivingHistory Test0$i.txt

    # Run diff and capture its return value.
	diff TestSol0$i.txt output.txt > /dev/null
	diff_val=$?
	
	# Output results based on diff's return value.
	if  [[ $diff_val != 0 ]]; then
		echo "fail (output does not match)"
	else
		echo "PASS!"
    fi
done

# Clean up any lingering .class files.
rm *.class

# Clean up the output files generated by this script.
rm output.txt